let contra = [
    {
        nombre:"Cristhian",
        email:"cehernandez@scl.edu.gt",
        password:"123456789"
    },
    {
        nombre:"Dereck",
        email:"dacarranza@scl.edu.gt",
        password:"123456789"
    },
    {
        nombre:"Anleu",
        email:"jbanleu@scl.edu.gt",
        password:"123456789"
    },
    {
        nombre:"Javier",
        email:"jemayen@scl.edu.gt",
        password:"123456789"
    },
    {
        nombre:"Yulian",
        email:"ysgaitan@scl.edu.gt",
        password:"123456789"
    },
    {
        nombre:"Emanuel",
        email:"eeordonez@scl.edu.gt",
        password:"123456789"
    },
    {
        nombre:"Danna",
        email:"dmosorio@scl.edu.gt",
        password:"123456789"
    },
    {
        nombre:"David",
        email:"jdaceituno@scl.edu.gt",
        password:"123456789"
    },
]
export {contra}